"""
nodes/color_data.py — 日本の伝統色 語彙データ（色系統でグループ化）

構造: (色系統キー, 色系統の日本語ラベル, [
    (漢字名, ローマ字読み, CLIPプロンプト向け英語表現, 16進カラーコード（参考値）),
    ...
])

注意: hex は歴史的・厳密な色彩学的定義ではなく、画像生成用途における
実用的な参考値。出典によって色味の解釈が異なる色名も多いため、
正確な学術的色見本が必要な用途には別途専門資料を参照すること。
"""

from __future__ import annotations

ColorEntry = tuple[str, str, str, str]
ColorGroup = tuple[str, str, list[ColorEntry]]

COLOR_GROUPS: list[ColorGroup] = [
    (
        "red_family", "紅・赤系統",
        [
            ("茜色", "akane-iro", "madder red", "#b7282e"),
            ("朱色", "shu-iro", "vermillion red-orange", "#eb6238"),
            ("紅色", "beni-iro", "crimson red", "#cf3721"),
            ("桜色", "sakura-iro", "pale cherry blossom pink", "#fef4f4"),
            ("鴇色", "toki-iro", "pale ibis pink", "#f2a0a1"),
            ("紅梅色", "koubai-iro", "plum blossom pink", "#e7609e"),
            ("撫子色", "nadeshiko-iro", "soft pink carnation", "#ee9ca7"),
            ("灰桜", "haizakura", "ash-gray cherry pink", "#e8d3d1"),
            ("東雲色", "shinonome-iro", "dawn pink", "#f19072"),
            ("桃色", "momo-iro", "peach pink", "#f7b8ac"),
            ("真紅", "shinku", "true crimson", "#c8102e"),
            ("韓紅", "karakurenai", "vivid deep crimson", "#d0104c"),
            ("猩々緋", "shoujouhi", "scarlet vermillion", "#eb6101"),
            ("銀朱", "ginshu", "silvery vermillion", "#e2571c"),
            ("弁柄色", "bengara-iro", "iron oxide red", "#9b4529"),
            ("赭色", "sohaku-iro", "reddish ochre", "#b8562f"),
            ("洗朱", "araishu", "washed vermillion", "#eb7a53"),
            ("今様色", "imayou-iro", "fashionable rose pink", "#ce7a89"),
            ("長春色", "choushun-iro", "dusty rose pink", "#d0827f"),
            ("珊瑚色", "sango-iro", "coral pink", "#f57f6c"),
            ("一斤染", "ikkonzome", "pale safflower pink", "#fadce4"),
            ("中紅", "nakabeni", "medium crimson", "#c85179"),
            ("退紅", "taikou", "faded pink", "#e8a0a0"),
            ("曙色", "akebono-iro", "daybreak pink-orange", "#f19e70"),
            ("珊瑚朱色", "sangoshu-iro", "coral vermillion", "#f2673a"),
            ("紅樺色", "benikaba-iro", "reddish birch brown", "#a24a44"),
            ("躑躅色", "tsutsuji-iro", "azalea pink-magenta", "#e1569c"),
            ("牡丹色", "botan-iro", "peony magenta", "#c93756"),
            ("薔薇色", "bara-iro", "rose red", "#e2618b"),
            ("苺色", "ichigo-iro", "strawberry red", "#c9184a"),
            ("林檎色", "ringo-iro", "apple red", "#d2222d"),
            ("小豆色", "azuki-iro", "red bean brown-red", "#96514d"),
            ("臙脂色", "enji-iro", "dark carmine red", "#a13d2f"),
            ("煉瓦色", "renga-iro", "brick red", "#a45a52"),
            ("栗梅", "kuriume", "chestnut-plum dark red", "#7f3735"),
            ("真朱", "shinshu", "true vermillion", "#e2521a"),
            ("深緋", "koki-hi", "deep scarlet, imperial rank color", "#9e3d3d"),
            ("今紅", "imabeni", "fresh crimson", "#d5405e"),
            ("薄紅", "usubeni", "light crimson", "#e87a90"),
            ("桜鼠", "sakuranezumi", "grayish cherry pink", "#d9c4c1"),
        ],
    ),
    (
        "blue_family", "藍・青系統",
        [
            ("藍色", "ai-iro", "deep indigo blue", "#1e50a2"),
            ("群青色", "gunjou-iro", "ultramarine blue", "#4c6cb3"),
            ("浅葱色", "asagi-iro", "light blue-green", "#00a3af"),
            ("瑠璃色", "ruri-iro", "lapis lazuli blue", "#1e50a2"),
            ("空色", "sora-iro", "sky blue", "#8fd8d2"),
            ("瓶覗", "kamenozoki", "faint pale blue", "#a8d8ea"),
            ("鉄紺", "tekkon", "dark iron navy", "#16264c"),
            ("縹色", "hanada-iro", "deep sky blue", "#0f5ea8"),
            ("花色", "hana-iro", "indigo blue, iris flower color", "#224b8f"),
            ("勿忘草色", "wasurenagusa-iro", "forget-me-not blue", "#7ba8d4"),
            ("水色", "mizu-iro", "pale water blue", "#bbe1ee"),
            ("紺青", "konjou", "deep prussian blue", "#123a71"),
            ("水浅葱", "mizuasagi", "pale aqua blue-green", "#98d1c0"),
            ("白群", "byakugun", "pale ultramarine", "#a4cee1"),
            ("紺色", "kon-iro", "navy blue", "#223a70"),
            ("濃紺", "noukon", "deep navy blue", "#16274a"),
            ("紺瑠璃", "konruri", "deep navy lapis blue", "#1a3f6e"),
            ("紺鼠", "konnezumi", "grayish navy", "#4d5c6f"),
            ("深川鼠", "fukagawanezumi", "bluish gray", "#a1b5b8"),
            ("錆青磁", "sabiseiji", "rustic celadon blue-gray", "#82a394"),
            ("浅縹", "asahanada", "light indigo blue", "#5088b5"),
            ("熨斗目花色", "noshimehanairo", "muted blue, formal kimono color", "#3a5e7d"),
            ("青褐", "aokachi", "dark blue-black", "#1c2f42"),
            ("露草色", "tsuyukusa-iro", "dayflower blue", "#5386ac"),
            ("新橋色", "shinbashi-iro", "bright turquoise blue", "#54c3c2"),
            ("天色", "sora-no-iro", "heavenly blue", "#4a89c4"),
            ("御納戸色", "onando-iro", "grayish teal blue", "#316745"),
            ("納戸色", "nando-iro", "dusty teal blue", "#286a7a"),
            ("勝色", "katsuiro", "deep blackish indigo, samurai armor color", "#0d2841"),
            ("青藍", "seiran", "blue indigo", "#274a78"),
            ("瑠璃紺", "rurikon", "deep lapis navy", "#1a3560"),
            ("秘色", "hisoku", "pale grayish celadon blue", "#b2d4d0"),
            ("高麗納戸", "kourainando", "muted korean teal blue", "#2c5c5e"),
            ("青碧", "seiheki", "blue-green jade color", "#1f7a72"),
            ("舛花色", "masuhanairo", "muted purplish blue", "#4a5a7d"),
            ("浜千鳥色", "hamachidori-iro", "pale shorebird blue-gray", "#a9c3cc"),
            ("新橋鼠", "shinbashinezumi", "grayish turquoise", "#8fb8b5"),
        ],
    ),
    (
        "green_family", "緑系統",
        [
            ("若草色", "wakakusa-iro", "young grass green", "#c3d825"),
            ("深緑", "fukamidori", "deep forest green", "#00553e"),
            ("抹茶色", "matcha-iro", "matcha green", "#c5b358"),
            ("萌黄色", "moegi-iro", "fresh yellow-green", "#aacf53"),
            ("若竹色", "wakatake-iro", "young bamboo green", "#68be8d"),
            ("千歳緑", "chitose-midori", "ancient pine deep green", "#38534d"),
            ("常磐色", "tokiwa-iro", "evergreen", "#007b43"),
            ("若苗色", "wakanae-iro", "young rice-seedling green", "#a8cb17"),
            ("萌葱色", "moegi", "spring onion green", "#7ba23f"),
            ("鶯色", "uguisu-iro", "bush warbler olive green", "#8b8b52"),
            ("鶯茶", "uguisucha", "brownish olive green", "#715c30"),
            ("苔色", "koke-iro", "moss green", "#75855b"),
            ("松葉色", "matsuba-iro", "pine needle green", "#3b6138"),
            ("柳色", "yanagi-iro", "willow green", "#a8c97f"),
            ("鶸色", "hiwa-iro", "siskin yellow-green", "#c5cf5c"),
            ("山鳩色", "yamabato-iro", "muted grayish green", "#828a4c"),
            ("利休鼠", "rikyuunezumi", "grayish green, tea-ceremony color", "#87977a"),
            ("千草鼠", "chigusanezumi", "muted blue-green gray", "#7d9384"),
            ("老竹色", "oitake-iro", "aged bamboo green", "#6f8875"),
            ("青竹色", "aotake-iro", "fresh bamboo green", "#008b45"),
            ("鶸萌黄", "hiwamoegi", "bright yellowish green", "#a9cc51"),
            ("海松色", "miru-iro", "seaweed dark olive green", "#68702c"),
            ("青磁色", "seiji-iro", "celadon porcelain green", "#8fbc94"),
            ("若緑", "wakamidori", "young leaf green", "#7ec488"),
            ("裏葉色", "urahairo", "pale leaf-underside green", "#c9d6a3"),
            ("白緑", "byakuroku", "pale mineral green", "#c2e2d4"),
            ("青丹", "aoni", "blue-green clay color", "#4a7466"),
            ("虫襖", "mushiao", "iridescent beetle green-black", "#41423e"),
            ("木賊色", "tokusa-iro", "horsetail dark green", "#294f3f"),
            ("山葵色", "wasabi-iro", "wasabi green", "#a8c97f"),
            ("柳鼠", "yanaginezumi", "grayish willow green", "#93997e"),
            ("藍海松茶", "aimirucha", "dark bluish olive green", "#4d5138"),
            ("錆鼠", "sabinezumi", "rusty gray-green", "#7d7d6b"),
            ("老松色", "oimatsu-iro", "aged pine green", "#6f7a4e"),
            ("萌黄鼠", "moeginezumi", "grayish spring green", "#93a15f"),
            ("苔鼠", "kokenezumi", "grayish moss green", "#7a8571"),
        ],
    ),
    (
        "yellow_orange_family", "黄・橙系統",
        [
            ("山吹色", "yamabuki-iro", "golden yellow", "#f8b500"),
            ("黄金色", "koganeiro", "golden", "#e8b902"),
            ("芥子色", "karashi-iro", "mustard yellow", "#d6a418"),
            ("蒲公英色", "tanpopo-iro", "dandelion yellow", "#fac03d"),
            ("柿色", "kaki-iro", "persimmon orange", "#ed6d3d"),
            ("卵色", "tamago-iro", "egg yolk yellow", "#fcd575"),
            ("支子色", "kuchinashi-iro", "gardenia yellow", "#f7c242"),
            ("刈安色", "kariyasu-iro", "bright grass yellow", "#f4d03f"),
            ("鬱金色", "ukon-iro", "turmeric yellow", "#eeb422"),
            ("女郎花", "ominaeshi", "golden-lace yellow", "#f2c649"),
            ("黄櫨染", "kourozen", "imperial amber-brown, emperor's color", "#a86b34"),
            ("黄丹", "outan", "reddish orange, crown-prince color", "#f08300"),
            ("蜜柑色", "mikan-iro", "mandarin orange", "#f08300"),
            ("橙色", "daidai-iro", "bitter orange", "#ee7800"),
            ("黄土色", "outsuchi-iro", "yellow ochre", "#c48a2c"),
            ("檸檬色", "remon-iro", "lemon yellow", "#f7e017"),
            ("雌黄", "shiou", "orpiment mineral yellow", "#eec14d"),
            ("山吹茶", "yamabukicha", "brownish golden yellow", "#c98615"),
            ("朽葉色", "kuchiba-iro", "withered leaf brown-yellow", "#a56a3a"),
            ("琥珀色", "kohaku-iro", "amber", "#c17a1f"),
            ("飴色", "ame-iro", "candy amber brown", "#a45a1f"),
            ("狐色", "kitsune-iro", "fox-fur brown-orange", "#c17c3f"),
            ("砂色", "suna-iro", "sand beige", "#d9c48b"),
            ("枯草色", "karekusa-iro", "withered grass tan", "#b8a165"),
            ("黄唐茶", "kigaracha", "yellowish brown", "#a9762e"),
            ("芒色", "susuki-iro", "pampas grass tan", "#c9a86a"),
            ("金茶", "kincha", "golden brown", "#c98216"),
            ("煎茶色", "sencha-iro", "green tea brown", "#8a6d3b"),
            ("肌色", "hadairo", "skin beige", "#f7cbaa"),
            ("人参色", "ninjin-iro", "carrot orange", "#e8781e"),
            ("黄檗色", "kihada-iro", "amur cork tree yellow", "#f4c531"),
            ("肉桂色", "nikkei-iro", "cinnamon brown", "#b3703f"),
        ],
    ),
    (
        "purple_family", "紫系統",
        [
            ("藤色", "fuji-iro", "wisteria purple", "#bbaee0"),
            ("紫紺", "shikon", "deep bluish purple", "#460e44"),
            ("江戸紫", "edo-murasaki", "edo purple", "#745399"),
            ("桔梗色", "kikyou-iro", "bellflower purple-blue", "#4c6cb3"),
            ("京紫", "kyo-murasaki", "Kyoto reddish purple", "#8b3a7c"),
            ("楝色", "ouchi-iro", "chinaberry pale purple", "#9d94c4"),
            ("二藍", "futaai", "layered indigo-crimson purple", "#7d4f83"),
            ("半色", "hashita-iro", "muted pale purple", "#c1a3c4"),
            ("菫色", "sumire-iro", "violet purple", "#7058a3"),
            ("菖蒲色", "ayame-iro", "iris purple", "#8f4694"),
            ("藤紫", "fujimurasaki", "wisteria bluish purple", "#8967aa"),
            ("紫苑色", "shion-iro", "aster light purple", "#867ba9"),
            ("古代紫", "kodai-murasaki", "ancient dusty purple", "#8a6bab"),
            ("深紫", "koki-murasaki", "deep royal purple", "#4a2d5e"),
            ("薄紫", "usumurasaki", "pale lilac purple", "#c3a4d1"),
            ("葡萄色", "budou-iro", "grape purple", "#5f3f5e"),
            ("茄子紺", "nasukon", "eggplant deep purple", "#453552"),
            ("滅紫", "kesemurasaki", "muted subdued purple", "#6e5768"),
            ("青紫", "aomurasaki", "blue-purple", "#6a5acd"),
            ("牡丹鼠", "botannezumi", "grayish peony purple", "#9c8296"),
            ("紅藤色", "benifuji-iro", "reddish wisteria purple", "#c98bbb"),
            ("藤鼠", "fujinezumi", "grayish wisteria purple", "#9a8fa8"),
            ("鳩羽鼠", "hatoba-nezumi", "grayish dove purple", "#8a7f8c"),
            ("鳩羽色", "hatoba-iro", "dove purple-gray", "#95859c"),
            ("葡萄鼠", "budou-nezumi", "grayish grape purple", "#6e5768"),
            ("竜胆色", "rindou-iro", "gentian purple-blue", "#5b4b8a"),
            ("桔梗鼠", "kikyounezumi", "grayish bellflower purple", "#75708f"),
            ("似せ紫", "nisemurasaki", "imitation purple dye color", "#7a5d8f"),
        ],
    ),
    (
        "neutral_family", "白・黒・鼠系統",
        [
            ("白銀", "shirogane", "silver white", "#c8c8cb"),
            ("漆黒", "shikkoku", "lacquer black", "#0e0e10"),
            ("生成り", "kinari", "undyed off-white", "#f8f4e6"),
            ("烏羽色", "karasuba-iro", "raven black with blue sheen", "#211c1c"),
            ("卯の花色", "unohana-iro", "deutzia flower white", "#f5f2e9"),
            ("銀鼠", "gin-nezu", "silver gray", "#91989f"),
            ("白練", "shironeri", "bleached raw silk white", "#f7f6ee"),
            ("胡粉色", "gofun-iro", "shell-powder white", "#f7f5ed"),
            ("象牙色", "zouge-iro", "ivory", "#f0e6d2"),
            ("亜麻色", "ama-iro", "flaxen beige", "#d9c9a3"),
            ("砥粉色", "toko-iro", "whetstone-powder tan", "#d6b98c"),
            ("灰白色", "kaihaku-shoku", "grayish white", "#e2ded6"),
            ("涅色", "kuri-iro", "deep blackish brown, dye-mud color", "#2b2420"),
            ("憲法黒茶", "kenpou-kurocha", "dark blackish brown", "#3b2f2a"),
            ("呉須色", "gosu-iro", "cobalt blue-gray porcelain color", "#3d5c6e"),
            ("消炭色", "keshizumi-iro", "charcoal ember gray", "#4d4c47"),
            ("墨色", "sumi-iro", "ink black", "#1c1c1c"),
            ("純白", "junpaku", "pure white", "#fefefe"),
            ("乳白色", "nyuuhaku-shoku", "milky white", "#f5f0e6"),
            ("月白", "geppaku", "pale moonlight blue-white", "#e6eef0"),
            ("利休白茶", "rikyuu-shiracha", "pale grayish beige", "#c9bfa8"),
            ("鈍色", "nibiiro", "dull mourning gray", "#727171"),
            ("白鼠", "shironezumi", "pale gray", "#d6d3cd"),
            ("憲法染", "kenpouzome", "deep blackish persimmon brown", "#4a3c34"),
            ("媚茶", "kobicha", "yellowish olive brown", "#7c5c33"),
            ("路考茶", "rokoucha", "grayish yellow-brown", "#8a6d4a"),
            ("焦茶", "kogecha", "scorched dark brown", "#3f2a1d"),
            ("栗色", "kuriiro", "chestnut brown", "#762f24"),
            ("弁柄茶", "bengaracha", "reddish iron-oxide brown", "#7a4633"),
            ("檜皮色", "hihada-iro", "cypress bark brown", "#78384f"),
        ],
    ),
]
