"""
nodes/material_data.py — material 語彙データ（大項目でグループ化）

構造: (大項目キー, 大項目の日本語ラベル, [
    (素材キー, 英語プロンプト語, 日本語ラベル),
    ...
])
"""

from __future__ import annotations

MaterialEntry = tuple[str, str, str]
MaterialGroup = tuple[str, str, list[MaterialEntry]]

MATERIAL_GROUPS: list[MaterialGroup] = [
    (
        "natural_fiber", "天然繊維",
        [
            ("silk", "silk fabric", "シルク"),
            ("wool", "wool texture", "ウール"),
            ("cotton", "cotton fabric", "コットン"),
            ("cashmere", "cashmere fabric", "カシミヤ"),
            ("angora", "angora wool texture", "アンゴラ"),
            ("alpaca_wool", "alpaca wool texture", "アルパカ"),
            ("mohair", "mohair fiber texture", "モヘア"),
            ("merino_wool", "merino wool texture", "メリノウール"),
            ("camel_hair", "camel hair texture", "キャメルヘア"),
            ("vicuna_wool", "vicuña wool texture, ultra-fine luxury fiber", "ビキューナ"),
            ("cheviot_wool", "cheviot wool texture", "シェビオットウール"),
            ("shetland_wool", "Shetland wool texture", "シェットランドウール"),
            ("karakul_wool", "karakul wool texture, curly fleece", "カラクール"),
            ("qiviut_wool", "qiviut musk-ox down fiber texture", "キビウット"),
            ("kapok_fiber", "kapok fiber texture", "カポック"),
            ("silk_noil", "silk noil raw-slub texture", "シルクノイル"),
            ("raw_silk_texture", "raw silk unrefined texture", "生糸テクスチャ"),
            ("pima_cotton", "Pima cotton fine texture", "ピマコットン"),
            ("egyptian_cotton", "Egyptian cotton luxury texture", "エジプトコットン"),
            ("organic_cotton", "organic cotton texture", "オーガニックコットン"),
            ("sea_island_cotton", "Sea Island cotton ultra-fine texture", "シーアイランドコットン"),
            ("linen_fabric", "linen fabric texture", "リネン（亜麻布）"),
            ("belgian_linen", "Belgian linen fine texture", "ベルギーリネン"),
            ("jute_fiber", "jute coarse natural fiber texture", "ジュート"),
            ("sisal_fiber", "sisal natural fiber texture", "サイザル麻"),
            ("pina_fiber", "piña pineapple leaf fiber texture", "ピニャ繊維"),
            ("banana_fiber", "banana leaf fiber texture", "バナナ繊維"),
        ],
    ),
    (
        "japanese_textile", "和素材",
        [
            ("washi", "washi paper texture, Japanese paper fabric", "和紙"),
            ("chirimen", "chirimen, Japanese silk crepe texture", "ちりめん"),
            ("kinran", "kinran, gold brocade fabric", "金襴"),
            ("nishijin_ori", "nishijin-ori, Japanese woven brocade texture", "西陣織"),
            ("tsumugi", "tsumugi, Japanese hand-woven pongee silk texture", "紬"),
            ("hemp_asa", "asa, Japanese hemp fabric texture", "麻"),
            ("ramie", "ramie fabric texture", "苧麻（ラミー）"),
            ("nishiki_brocade", "nishiki, Japanese luxury brocade texture", "錦"),
            ("habutai", "habutai, smooth plain-weave silk texture", "羽二重"),
            ("sha_gauze_silk", "sha, Japanese sheer gauze silk texture", "紗"),
            ("ro_summer_gauze", "ro, Japanese open-weave summer silk texture", "絽"),
            ("rinzu_damask", "rinzu, Japanese figured satin damask texture", "綸子"),
            ("omeshi_silk", "omeshi, Japanese crepe silk texture", "御召"),
            ("kasuri_weave", "kasuri, Japanese ikat-woven texture", "絣織り"),
            ("yuki_tsumugi", "Yuki-tsumugi, fine handspun silk texture", "結城紬"),
            ("oshima_tsumugi", "Ōshima-tsumugi, mud-dyed silk texture", "大島紬"),
            ("sakiori_weave", "sakiori, Japanese rag-woven texture", "裂織"),
            ("mofuku_silk", "mofuku black silk mourning fabric texture", "喪服用黒羽二重"),
        ],
    ),
    (
        "synthetic_fiber", "化学繊維",
        [
            ("rayon", "rayon fabric", "レーヨン"),
            ("polyester", "polyester fabric", "ポリエステル"),
            ("spandex_lycra", "stretch spandex/lycra fabric", "スパンデックス（ライクラ）"),
            ("pu_leather", "PU faux leather texture", "合成皮革（PUレザー）"),
            ("neoprene", "neoprene fabric texture", "ネオプレン"),
            ("nylon", "nylon fabric texture", "ナイロン"),
            ("acrylic_fiber", "acrylic knit fiber texture", "アクリル繊維"),
            ("acetate_fabric", "acetate satin-like fabric texture", "アセテート"),
            ("triacetate_fabric", "triacetate fabric texture", "トリアセテート"),
            ("modal_fabric", "modal fabric texture", "モダール"),
            ("tencel_lyocell", "Tencel lyocell fabric texture", "テンセル（リヨセル）"),
            ("viscose_fabric", "viscose fabric texture", "ビスコース"),
            ("microfiber_fabric", "microfiber fabric texture", "マイクロファイバー"),
            ("elastane_blend", "elastane stretch blend fabric", "エラスタン混紡"),
            ("polyurethane_coated_fabric", "polyurethane-coated fabric texture", "ポリウレタンコーティング生地"),
            ("gore_tex_membrane", "waterproof breathable membrane texture", "ゴアテックス素材"),
            ("softshell_fabric", "softshell technical fabric texture", "ソフトシェル素材"),
            ("ripstop_nylon", "ripstop nylon fabric texture", "リップストップナイロン"),
            ("ballistic_nylon", "ballistic nylon heavy-duty texture", "バリスティックナイロン"),
            ("kevlar_reinforced", "Kevlar-reinforced fabric texture", "ケブラー補強素材"),
        ],
    ),
    (
        "leather_fur", "皮革・毛皮",
        [
            ("leather", "leather texture", "レザー"),
            ("faux_fur", "faux fur texture", "フェイクファー"),
            ("suede_texture", "suede texture", "スエード"),
            ("shearling_texture", "shearling sheepskin texture", "シアリング"),
            ("python_leather", "python snakeskin leather texture", "パイソンレザー"),
            ("crocodile_leather", "crocodile leather texture", "クロコダイルレザー"),
            ("ostrich_leather", "ostrich leather quill texture", "オーストリッチレザー"),
            ("patent_leather", "glossy patent leather texture", "パテントレザー（エナメル）"),
            ("nubuck_leather", "nubuck leather texture", "ヌバックレザー"),
            ("distressed_leather", "distressed vintage leather texture", "ダメージレザー"),
            ("chinchilla_fur", "chinchilla fur texture", "チンチラファー"),
            ("mink_fur", "mink fur texture", "ミンクファー"),
            ("fox_fur", "fox fur texture", "フォックスファー"),
            ("rabbit_fur", "rabbit fur texture", "ラビットファー"),
            ("sheepskin_fur", "sheepskin fur texture", "シープスキン"),
            ("pony_hair_texture", "pony hair calf texture", "ポニーヘアレザー"),
            ("lizard_leather", "lizard skin leather texture", "リザードレザー"),
            ("stingray_leather", "stingray leather texture", "エイ革（ガルーシャ）"),
            ("calfskin_leather", "soft calfskin leather texture", "カーフスキンレザー"),
            ("saffiano_leather", "saffiano cross-hatch textured leather", "サフィアーノレザー"),
            ("velvet_suede", "velvety brushed suede texture", "ベルベットスエード"),
        ],
    ),
    (
        "woven_special", "織り・特殊質感",
        [
            ("denim", "denim fabric", "デニム"),
            ("velvet", "velvet texture", "ベルベット"),
            ("satin", "satin sheen", "サテン"),
            ("lace", "lace fabric", "レース"),
            ("chiffon", "sheer chiffon", "シフォン"),
            ("vinyl", "glossy vinyl", "ビニール（光沢）"),
            ("organza", "sheer organza fabric", "オーガンジー"),
            ("tulle", "tulle netting fabric", "チュール"),
            ("brocade_western", "brocade fabric texture", "ブロケード"),
            ("tweed", "tweed fabric texture", "ツイード"),
            ("corduroy", "corduroy ribbed texture", "コーデュロイ"),
            ("mesh_fabric", "sheer mesh fabric", "メッシュ生地"),
            ("gauze_fabric", "lightweight gauze fabric texture", "ガーゼ"),
            ("muslin_fabric", "muslin plain-weave fabric texture", "モスリン"),
            ("poplin_fabric", "poplin crisp fabric texture", "ポプリン"),
            ("twill_fabric", "twill weave fabric texture", "ツイル（綾織り）"),
            ("gabardine_fabric", "gabardine tightly-woven texture", "ギャバジン"),
            ("jersey_knit", "jersey knit fabric texture", "ジャージーニット"),
            ("taffeta_fabric", "taffeta crisp sheen fabric", "タフタ"),
            ("dupioni_silk", "dupioni silk slubbed texture", "デュピオンシルク"),
            ("shantung_silk", "shantung silk textured fabric", "シャンタン"),
            ("georgette_fabric", "georgette crepe fabric texture", "ジョーゼット"),
            ("crepe_de_chine", "crepe de chine fabric texture", "クレープデシン"),
            ("batiste_fabric", "batiste fine sheer fabric", "バティスト"),
            ("voile_fabric", "voile lightweight sheer fabric", "ボイル"),
            ("seersucker_fabric", "seersucker puckered texture", "シアサッカー"),
            ("chambray_fabric", "chambray lightweight woven texture", "シャンブレー"),
            ("flannel_fabric", "flannel brushed texture", "フランネル"),
            ("fleece_fabric", "fleece soft pile texture", "フリース"),
            ("terry_cloth", "terry cloth looped pile texture", "パイル地（テリークロス）"),
            ("jacquard_fabric", "jacquard woven texture", "ジャカード生地"),
            ("moire_fabric", "moire watered-silk texture", "モアレ"),
            ("lame_fabric", "lamé metallic-thread fabric", "ラメ生地"),
            ("boucle_fabric", "bouclé looped-yarn texture", "ブークレ"),
            ("chenille_fabric", "chenille tufted texture", "シェニール"),
            ("velour_fabric", "velour plush texture", "ベロア"),
            ("crushed_velvet", "crushed velvet texture", "クラッシュベルベット"),
            ("panne_velvet", "panne velvet flattened sheen texture", "パンヌベルベット"),
            ("devore_velvet", "devoré burnout velvet texture", "デヴォレベルベット（オパール加工）"),
            ("matelasse_fabric", "matelassé quilted texture", "マトラッセ"),
            ("cloque_fabric", "cloqué blistered texture", "クロッケ"),
            ("ottoman_fabric", "ottoman ribbed texture", "オットマン"),
            ("faille_fabric", "faille ribbed silk texture", "フェイユ"),
            ("grosgrain_fabric", "grosgrain ribbed texture", "グログラン"),
            ("bengaline_fabric", "bengaline ribbed texture", "ベンガリーヌ"),
            ("barathea_fabric", "barathea pebbled texture", "バラシア"),
            ("melton_wool", "melton dense wool texture", "メルトンウール"),
            ("loden_wool", "loden felted wool texture", "ロデンウール"),
            ("boiled_wool", "boiled wool felted texture", "煮込みウール"),
            ("alcantara_fabric", "Alcantara microfiber suede texture", "アルカンターラ"),
            ("technical_mesh", "technical performance mesh texture", "テクニカルメッシュ"),
            ("scuba_fabric", "scuba neoprene-like knit texture", "スキューバニット"),
            ("ponte_knit", "ponte double-knit texture", "ポンチニット"),
            ("double_knit_fabric", "double knit fabric texture", "ダブルニット"),
            ("rib_knit", "rib knit texture", "リブニット"),
            ("cable_knit_fabric", "cable knit texture", "ケーブルニット"),
            ("waffle_knit", "waffle knit texture", "ワッフルニット"),
            ("french_terry", "French terry loop-back texture", "フレンチテリー"),
            ("sweatshirt_fleece", "sweatshirt fleece texture", "スウェットフリース"),
            ("minky_fabric", "minky plush texture", "ミンキー"),
            ("sherpa_fleece", "sherpa fleece pile texture", "シェルパフリース"),
            ("holographic_vinyl", "holographic vinyl texture", "ホログラムビニール"),
            ("iridescent_film_fabric", "iridescent film-coated fabric texture", "イリデセントフィルム生地"),
            ("cellophane_fabric", "cellophane crinkled texture", "セロファン素材"),
            ("metallic_foil_fabric", "metallic foil-printed fabric texture", "メタリック箔生地"),
        ],
    ),
    (
        "world_material", "世界の伝統素材",
        [
            ("khadi_cotton", "khadi hand-spun cotton texture", "カディコットン"),
            ("harris_tweed", "Harris Tweed hand-woven texture", "ハリスツイード"),
            ("donegal_tweed", "Donegal tweed flecked texture", "ドニゴールツイード"),
            ("liberty_lawn_cotton", "Liberty lawn fine cotton texture", "リバティローン"),
            ("madras_cotton", "madras plaid cotton texture", "マドラスコットン"),
            ("khaddar_fabric", "khaddar coarse handwoven texture", "カダル"),
            ("batik_cotton", "batik wax-dyed cotton texture", "バティックコットン"),
            ("songket_silk", "songket gold-brocade silk texture", "ソンケットシルク"),
            ("ikat_cotton", "ikat resist-dyed cotton texture", "イカットコットン"),
            ("alpaca_boucle", "alpaca bouclé blend texture", "アルパカブークレ"),
            ("mudcloth_cotton", "bogolan mudcloth cotton texture", "ムドクロス（泥染め布）"),
            ("kente_cotton", "kente hand-woven cotton texture", "ケンテコットン"),
            ("adire_cotton", "adire resist-dyed cotton texture", "アディレコットン"),
            ("huipil_cotton", "huipil hand-woven cotton texture", "ウイピルコットン"),
            ("alpaca_felt", "alpaca wool felt texture", "アルパカフェルト"),
            ("boiled_felt", "traditional boiled felt texture", "煮込みフェルト"),
            ("mongolian_felt", "Mongolian wool felt texture", "モンゴルフェルト"),
            ("peruvian_alpaca_weave", "Peruvian hand-woven alpaca texture", "ペルーアルパカ織り"),
            ("guatemalan_cotton_weave", "Guatemalan hand-woven cotton texture", "グアテマラ手織りコットン"),
            ("thai_silk_texture", "Thai silk lustrous texture", "タイシルクテクスチャ"),
            ("indian_zari_silk", "Indian zari-woven silk texture", "インドザリシルク"),
            ("chinese_silk_brocade", "Chinese silk brocade texture", "中国絹錦"),
            ("korean_ramie_mosi", "Korean mosi fine ramie texture", "苧布（モシ）"),
        ],
    ),
    (
        "modern_industrial", "モダン・工業素材",
        [
            ("felt_fabric", "felt fabric texture", "フェルト"),
            ("canvas_fabric", "canvas heavy-duty texture", "キャンバス"),
            ("burlap_fabric", "burlap coarse texture", "麻袋地（バーラップ）"),
            ("oilcloth_fabric", "oilcloth coated texture", "オイルクロス"),
            ("waxed_cotton", "waxed cotton texture", "ワックスドコットン"),
            ("cork_fabric", "cork fabric texture", "コルク生地"),
            ("bamboo_fiber_fabric", "bamboo fiber fabric texture", "竹繊維生地"),
            ("recycled_pet_fabric", "recycled PET fiber fabric texture", "再生PET繊維生地"),
            ("carbon_fiber_texture", "carbon fiber woven texture", "カーボンファイバー"),
            ("metallic_mesh_fabric", "metallic chainmail mesh texture", "メタリックメッシュ（チェインメイル）"),
            ("rubber_latex_texture", "rubber latex glossy texture", "ラバー・ラテックス素材"),
            ("silicone_coated_fabric", "silicone-coated fabric texture", "シリコンコーティング生地"),
            ("tyvek_fabric", "Tyvek paper-like synthetic texture", "タイベック素材"),
            ("3d_knit_fabric", "seamless 3D-knit fabric texture", "3Dニット"),
            ("laser_cut_leather", "laser-cut perforated leather texture", "レーザーカットレザー"),
            ("perforated_leather", "perforated breathable leather texture", "パンチングレザー"),
            ("embossed_leather", "embossed textured leather", "型押しレザー"),
            ("cork_leather_alternative", "cork-based vegan leather texture", "コルクレザー（代替皮革）"),
            ("pinatex_leather_alternative", "pineapple-leaf leather alternative texture", "パイナップルレザー（ピニャテックス）"),
            ("mushroom_leather_alternative", "mycelium mushroom leather alternative texture", "マッシュルームレザー"),
            ("recycled_denim_fabric", "recycled denim fiber texture", "再生デニム素材"),
            ("hemp_canvas", "hemp canvas heavy-duty texture", "麻キャンバス"),
            ("technical_softshell_bonded", "bonded technical softshell texture", "ボンディングソフトシェル"),
            ("thermal_quilted_fabric", "thermal quilted insulation texture", "サーマルキルティング素材"),
            ("water_repellent_coated_cotton", "water-repellent coated cotton texture", "撥水コーティングコットン"),
            ("biodegradable_bioplastic_fabric", "biodegradable bioplastic-fiber fabric texture", "生分解性バイオプラスチック素材"),
        ],
    ),
]
