"""
nodes/pattern_data.py — pattern 語彙データ（大項目でグループ化）

構造: (大項目キー, 大項目の日本語ラベル, [
    (パターンキー, 英語プロンプト語, 日本語ラベル),
    ...
])
"""

from __future__ import annotations

PatternEntry = tuple[str, str, str]
PatternGroup = tuple[str, str, list[PatternEntry]]

PATTERN_GROUPS: list[PatternGroup] = [
    (
        "geometric", "幾何学柄",
        [
            ("striped", "striped pattern", "ストライプ"),
            ("polka_dot", "polka dot pattern", "水玉"),
            ("plaid", "plaid pattern", "タータンチェック"),
            ("checkered", "checkered pattern", "チェック柄"),
            ("geometric", "geometric pattern", "幾何学模様"),
            ("houndstooth", "houndstooth pattern", "千鳥格子"),
            ("arabesque_tile", "arabesque geometric tile pattern", "アラベスク幾何学タイル柄"),
            ("mandala", "mandala pattern", "曼荼羅柄"),
            ("damask", "damask pattern", "ダマスク柄"),
            ("hishi", "hishi, Japanese diamond lattice pattern", "菱文様"),
            ("gingham", "gingham check pattern", "ギンガムチェック"),
            ("chevron", "chevron zigzag pattern", "シェブロン柄"),
            ("herringbone", "herringbone weave pattern", "ヘリンボーン柄"),
            ("ogee", "ogee pattern, Persian/Islamic curved lattice motif", "オジー柄（ペルシャ格子）"),
            ("pinstripe", "pinstripe pattern", "ピンストライプ"),
            ("chalk_stripe", "chalk stripe pattern", "チョークストライプ"),
            ("pencil_stripe", "pencil stripe pattern", "ペンシルストライプ"),
            ("windowpane_check", "windowpane check pattern", "ウィンドウペンチェック"),
            ("tattersall_check", "tattersall check pattern", "タターソールチェック"),
            ("glen_check", "glen check pattern, Prince of Wales check", "グレンチェック"),
            ("argyle", "argyle diamond pattern", "アーガイル柄"),
            ("harlequin_diamond", "harlequin diamond pattern", "アルルカン柄"),
            ("basketweave_pattern", "basketweave printed pattern", "バスケット織柄"),
            ("honeycomb_pattern", "honeycomb hexagon pattern", "ハニカム柄"),
            ("op_art_pattern", "optical art geometric pattern", "オプアート柄"),
            ("art_deco_pattern", "art deco geometric pattern", "アールデコ柄"),
            ("bauhaus_pattern", "Bauhaus geometric pattern", "バウハウス柄"),
            ("pixel_pattern", "pixelated digital pattern", "ピクセル柄"),
            ("maze_pattern", "maze labyrinth pattern", "迷路柄"),
            ("triangle_pattern", "repeating triangle pattern", "三角形柄"),
            ("concentric_circle_pattern", "concentric circle pattern", "同心円柄"),
            ("micro_polka_dot", "micro polka dot pattern", "マイクロ水玉"),
            ("pin_dot_pattern", "pin dot pattern", "ピンドット柄"),
            ("coin_dot_pattern", "coin dot pattern", "コインドット柄"),
            ("candy_stripe_pattern", "candy stripe pattern", "キャンディストライプ"),
            ("awning_stripe_pattern", "awning stripe pattern", "オーニングストライプ"),
            ("breton_stripe_pattern", "breton stripe pattern", "ボーダー柄（ブルトンストライプ）"),
            ("diagonal_stripe_pattern", "diagonal stripe pattern", "ダイアゴナルストライプ"),
            ("variegated_stripe_pattern", "variegated multi-width stripe pattern", "変則幅ストライプ"),
            ("buffalo_check_pattern", "buffalo check pattern", "バッファローチェック"),
            ("madras_check_pattern", "madras check pattern", "マドラスチェック"),
            ("shepherd_check_pattern", "shepherd's check pattern", "シェパードチェック"),
            ("gunclub_check_pattern", "gun club check pattern", "ガンクラブチェック"),
            ("diamond_lattice_pattern", "diamond lattice pattern", "ダイヤモンドラティス柄"),
            ("trellis_pattern", "trellis lattice pattern", "トレリス柄"),
            ("quatrefoil_pattern", "quatrefoil pattern", "カトルフォイル柄"),
            ("moorish_lattice_pattern", "Moorish geometric lattice pattern", "ムーア風格子柄"),
            ("spiral_pattern", "spiral geometric pattern", "螺旋柄"),
            ("zigzag_pattern", "zigzag pattern", "ジグザグ柄"),
            ("brick_pattern", "brick-laid geometric pattern", "レンガ柄"),
            ("houndstooth_micro_pattern", "micro houndstooth pattern", "マイクロ千鳥格子"),
            ("basketweave_check_pattern", "basketweave check pattern", "バスケット風チェック柄"),
        ],
    ),
    (
        "nature_motif", "自然モチーフ柄",
        [
            ("floral", "floral pattern", "花柄"),
            ("animal_print", "animal print pattern", "アニマル柄"),
            ("camouflage", "camouflage pattern", "迷彩柄"),
            ("paisley", "paisley pattern", "ペイズリー柄"),
            ("sakura_pattern", "sakura cherry blossom pattern", "桜柄"),
            ("kumo", "kumo, Japanese stylized cloud pattern", "雲文様"),
            ("leopard_print", "leopard print pattern", "レオパード柄"),
            ("zebra_print", "zebra stripe print pattern", "ゼブラ柄"),
            ("tiger_stripe_print", "tiger stripe print pattern", "タイガー柄"),
            ("snake_print", "snakeskin print pattern", "スネーク柄"),
            ("giraffe_print", "giraffe spot print pattern", "ジラフ柄"),
            ("cow_print", "cow spot print pattern", "カウ柄"),
            ("butterfly_pattern", "butterfly motif pattern", "蝶柄"),
            ("bird_motif_pattern", "bird motif pattern", "鳥柄"),
            ("peacock_feather_pattern", "peacock feather pattern", "孔雀羽柄"),
            ("fish_scale_pattern", "fish scale pattern", "魚鱗柄"),
            ("leaf_pattern", "botanical leaf pattern", "リーフ柄"),
            ("palm_leaf_pattern", "tropical palm leaf pattern", "パームリーフ柄"),
            ("botanical_print", "botanical illustration print", "ボタニカル柄"),
            ("tropical_print", "tropical print pattern", "トロピカル柄"),
            ("wildflower_pattern", "wildflower meadow pattern", "ワイルドフラワー柄"),
            ("rose_pattern", "rose floral pattern", "薔薇柄"),
            ("ditsy_floral", "ditsy small-scale floral pattern", "小花柄"),
            ("large_scale_floral", "large-scale floral pattern", "大花柄"),
            ("coral_reef_pattern", "coral reef motif pattern", "珊瑚礁柄"),
            ("wave_pattern", "ocean wave pattern", "波柄"),
            ("cloud_pattern", "stylized cloud pattern", "雲柄"),
            ("mountain_range_pattern", "mountain range silhouette pattern", "山並み柄"),
            ("star_night_sky_pattern", "starry night sky pattern", "星空柄"),
            ("snowflake_pattern", "snowflake pattern", "雪の結晶柄"),
            ("dragonfly_motif_pattern", "dragonfly motif pattern", "トンボ柄"),
            ("bee_motif_pattern", "bee motif pattern", "蜜蜂柄"),
            ("owl_motif_pattern", "owl motif pattern", "フクロウ柄"),
            ("fox_motif_pattern", "fox motif pattern", "狐柄"),
            ("rabbit_motif_pattern", "rabbit motif pattern", "うさぎ柄"),
            ("deer_motif_pattern", "deer motif pattern", "鹿柄"),
            ("seashell_pattern", "seashell motif pattern", "貝殻柄"),
            ("starfish_pattern", "starfish motif pattern", "ヒトデ柄"),
            ("mushroom_motif_pattern", "mushroom motif pattern", "きのこ柄"),
            ("acorn_motif_pattern", "acorn motif pattern", "どんぐり柄"),
            ("pinecone_motif_pattern", "pinecone motif pattern", "松ぼっくり柄"),
            ("bamboo_motif_pattern", "bamboo motif pattern", "竹柄"),
            ("pine_motif_pattern", "pine tree motif pattern", "松柄"),
            ("ivy_vine_pattern", "ivy vine pattern", "アイビー柄"),
            ("cactus_motif_pattern", "cactus motif pattern", "サボテン柄"),
            ("citrus_fruit_pattern", "citrus fruit motif pattern", "柑橘柄"),
            ("cherry_fruit_pattern", "cherry fruit motif pattern", "チェリー柄"),
            ("strawberry_motif_pattern", "strawberry motif pattern", "いちご柄"),
            ("pineapple_motif_pattern", "pineapple motif pattern", "パイナップル柄"),
        ],
    ),
    (
        "wagara", "和柄",
        [
            ("seigaiha", "seigaiha, Japanese blue wave pattern", "青海波"),
            ("asanoha", "asanoha, Japanese hemp-leaf geometric pattern", "麻の葉"),
            ("ichimatsu", "ichimatsu, Japanese checkerboard pattern", "市松模様"),
            ("karakusa", "karakusa, Japanese arabesque vine pattern", "唐草模様"),
            ("kikkou", "kikkou, Japanese tortoiseshell hexagon pattern", "亀甲柄"),
            ("shippou", "shippou, Japanese interlocking circles pattern", "七宝柄"),
            ("raimon", "raimon, Japanese thunder/key-fret pattern", "雷紋"),
            ("uroko", "uroko, Japanese triangular scale pattern", "鱗文様"),
            ("tatewaku", "tatewaku, Japanese rising vapor stripe pattern", "立涌"),
            ("sayagata", "sayagata, Japanese interlocking key-fret pattern", "紗綾形"),
            ("kagome", "kagome, Japanese woven basket-weave star pattern", "籠目"),
            ("matsukawabishi", "matsukawabishi, Japanese pine-bark diamond pattern", "松皮菱"),
            ("yagasuri", "yagasuri, Japanese arrow-feather pattern", "矢絣"),
            ("genjiguruma", "genji-guruma, Japanese ox-cart wheel pattern", "源氏車"),
            ("hanabishi", "hanabishi, Japanese flower diamond pattern", "花菱"),
            ("kikumon", "kiku, Japanese chrysanthemum pattern", "菊文様"),
            ("botan_karakusa", "botan karakusa, Japanese peony arabesque pattern", "牡丹唐草"),
            ("nami_pattern", "nami, Japanese stylized wave pattern", "波文様"),
            ("chidori_pattern", "chidori, Japanese plover bird pattern", "千鳥文様"),
            ("tsuru_pattern", "tsuru, Japanese crane bird pattern", "鶴文様"),
            ("kissho_pattern", "kissho, Japanese auspicious symbol pattern", "吉祥文様"),
            ("shima_gara_stripe", "shima-gara, Japanese traditional stripe pattern", "縞柄"),
            ("edo_komon_dot", "edo-komon, Japanese fine dot-stencil pattern", "江戸小紋"),
            ("kagome_asanoha_mix", "kagome-asanoha combined lattice pattern", "籠目麻の葉複合柄"),
            ("bishamon_kikkou", "bishamon-kikkou, layered hexagon pattern", "毘沙門亀甲"),
            ("sakura_kissho", "sakura kissho, auspicious cherry blossom pattern", "桜吉祥文"),
            ("fujimusume_wisteria", "fuji, Japanese wisteria pattern", "藤文様"),
            ("momiji_maple_pattern", "momiji, Japanese maple leaf pattern", "紅葉文様"),
            ("ume_plum_blossom_pattern", "ume, Japanese plum blossom pattern", "梅文様"),
            ("kikko_hanabishi", "kikko-hanabishi, hexagon-diamond combined pattern", "亀甲花菱"),
            ("sekka_snow_crystal", "sekka, Japanese stylized snow crystal pattern", "雪華文様"),
            ("uzura_quail_pattern", "uzura, Japanese quail bird pattern", "鶉文様"),
            ("ogi_fan_pattern", "ogi, Japanese folding fan pattern", "扇文様"),
            ("kumo_karakusa", "kumo-karakusa, cloud arabesque pattern", "雲唐草"),
        ],
    ),
    (
        "world_textile", "世界の織物柄",
        [
            ("toile", "toile de jouy pattern", "トワル・ド・ジュイ柄"),
            ("ikat", "ikat pattern", "絣（イカット）柄"),
            ("kente", "kente cloth pattern", "ケンテ柄"),
            ("fair_isle", "fair isle pattern", "フェアアイル柄"),
            ("tartan", "tartan pattern", "タータン柄"),
            ("shweshwe_pattern", "shweshwe print pattern", "シュエシュエ柄"),
            ("mudcloth_pattern", "bogolan mudcloth pattern", "ボゴランムドクロス柄"),
            ("suzani_pattern", "suzani embroidered pattern", "スザニ柄"),
            ("otomi_pattern", "otomi embroidered animal pattern", "オトミ柄"),
            ("molas_pattern", "mola reverse-applique pattern", "モラ柄"),
            ("shibori_pattern", "shibori tie-dye pattern", "絞り柄"),
            ("batik_pattern", "batik wax-resist pattern", "バティック柄"),
            ("songket_pattern", "songket gold-thread woven pattern", "ソンケット柄"),
            ("kilim_pattern", "kilim woven rug pattern", "キリム柄"),
            ("paisley_persian", "Persian paisley pattern", "ペルシャペイズリー柄"),
            ("indian_block_print_pattern", "Indian block-print motif pattern", "インドブロックプリント柄"),
            ("bandhani_pattern", "bandhani tie-dye dot pattern", "バンダニ柄"),
            ("aztec_pattern", "Aztec geometric pattern", "アステカ柄"),
            ("navajo_pattern", "Navajo woven blanket pattern", "ナバホ柄"),
            ("huipil_pattern", "huipil geometric weave pattern", "ウイピル柄"),
            ("scandinavian_pattern", "Scandinavian folk pattern", "北欧民族柄"),
            ("marimekko_style_pattern", "bold Scandinavian floral print pattern", "北欧大花柄"),
            ("moroccan_tile_pattern", "Moroccan zellige tile pattern", "モロッコタイル柄"),
            ("provencal_pattern", "Provençal French country print pattern", "プロヴァンス柄"),
            ("liberty_print_pattern", "Liberty-style floral print pattern", "リバティプリント柄"),
            ("ankara_wax_print_pattern", "Ankara wax print pattern", "アンカラワックスプリント柄"),
            ("hmong_batik_pattern", "Hmong indigo batik pattern", "モン族バティック柄"),
            ("peruvian_textile_pattern", "Peruvian woven textile pattern", "ペルー織物柄"),
            ("guatemalan_ikat_pattern", "Guatemalan ikat weave pattern", "グアテマラ絣柄"),
            ("indonesian_batik_pattern", "Indonesian batik pattern", "インドネシアバティック柄"),
            ("thai_silk_pattern", "Thai silk woven pattern", "タイシルク柄"),
            ("chinese_cloud_pattern", "Chinese cloud collar pattern", "雲肩文様"),
            ("chinese_dragon_pattern", "Chinese dragon motif pattern", "龍文様"),
            ("chinese_phoenix_pattern", "Chinese phoenix motif pattern", "鳳凰文様"),
            ("korean_bojagi_pattern", "Korean bojagi patchwork pattern", "ポジャギ柄"),
            ("mongolian_motif_pattern", "Mongolian felt applique pattern", "モンゴル文様"),
            ("russian_khokhloma_pattern", "Russian khokhloma floral pattern", "ホフロマ柄"),
            ("hungarian_folk_pattern", "Hungarian folk embroidery pattern", "ハンガリー民族柄"),
            ("greek_key_pattern", "Greek key meander pattern", "ギリシャキー柄"),
        ],
    ),
    (
        "art_style", "アートスタイル柄",
        [
            ("art_nouveau_pattern", "art nouveau flowing pattern", "アールヌーヴォー柄"),
            ("bohemian_pattern", "bohemian eclectic print pattern", "ボヘミアン柄"),
            ("psychedelic_pattern", "psychedelic swirl pattern", "サイケデリック柄"),
            ("pop_art_pattern", "pop art graphic pattern", "ポップアート柄"),
            ("watercolor_pattern", "watercolor wash pattern", "水彩柄"),
            ("abstract_brushstroke_pattern", "abstract brushstroke pattern", "抽象筆致柄"),
            ("marble_texture_pattern", "marbled stone texture pattern", "マーブル柄"),
            ("tie_dye_swirl_pattern", "tie-dye swirl pattern", "タイダイ渦柄"),
            ("gradient_ombre_pattern", "gradient ombre color pattern", "グラデーション柄"),
            ("collage_print_pattern", "mixed-media collage print pattern", "コラージュ柄"),
            ("cubist_pattern", "cubist geometric pattern", "キュビズム柄"),
            ("surrealist_pattern", "surrealist dreamlike pattern", "シュルレアリスム柄"),
            ("impressionist_pattern", "impressionist brushstroke floral pattern", "印象派風柄"),
            ("graffiti_tag_pattern", "graffiti tag style pattern", "グラフィティタグ柄"),
        ],
    ),
    (
        "era_style", "時代スタイル柄",
        [
            ("70s_retro_pattern", "1970s retro groovy pattern", "70年代レトロ柄"),
            ("80s_neon_pattern", "1980s neon geometric pattern", "80年代ネオン柄"),
            ("90s_grunge_pattern", "1990s grunge plaid pattern", "90年代グランジ柄"),
            ("victorian_damask_pattern", "Victorian era damask pattern", "ヴィクトリア朝ダマスク柄"),
            ("mid_century_modern_pattern", "mid-century modern geometric pattern", "ミッドセンチュリーモダン柄"),
            ("y2k_pattern", "Y2K futuristic graphic pattern", "Y2Kパターン"),
            ("baroque_pattern", "baroque ornamental pattern", "バロック柄"),
            ("rococo_pattern", "rococo floral scroll pattern", "ロココ柄"),
            ("edwardian_lace_pattern", "Edwardian lace-inspired pattern", "エドワード朝レース柄"),
            ("space_age_pattern", "1960s space age graphic pattern", "スペースエイジ柄"),
            ("art_deco_fan_pattern", "art deco fan-shaped pattern", "アールデコ扇柄"),
            ("memphis_design_pattern", "Memphis design 1980s pattern", "メンフィスデザイン柄"),
        ],
    ),
]
