"""
nodes/subject_data.py — subject_hint（対象語）語彙データ（大項目でグループ化）

構造: (大項目キー, 大項目の日本語ラベル, [
    (日本語, 英語),
    ...
])
"""

from __future__ import annotations

SubjectEntry = tuple[str, str]
SubjectGroup = tuple[str, str, list[SubjectEntry]]

SUBJECT_GROUPS: list[SubjectGroup] = [
    (
        "japanese_wear", "和装",
        [
            ("着物", "kimono"),
            ("浴衣", "yukata"),
            ("帯", "obi"),
            ("羽織", "haori"),
            ("袴", "hakama"),
            ("甚平", "jinbei"),
            ("振袖", "furisode"),
            ("留袖", "tomesode"),
            ("訪問着", "houmongi"),
            ("小紋", "komon kimono"),
            ("色無地", "iromuji kimono"),
            ("道中着", "doucyugi travel coat"),
            ("半纏", "hanten jacket"),
            ("褞袍", "dotera padded robe"),
            ("襦袢", "juban undergarment"),
            ("足袋", "tabi socks"),
            ("草履", "zori sandals"),
            ("下駄", "geta sandals"),
            ("巾着", "kinchaku drawstring pouch"),
            ("扇子", "folding fan"),
            ("裃", "kamishimo formal samurai attire"),
            ("陣羽織", "jinbaori battle surcoat"),
            ("十二単", "juunihitoe twelve-layer robe"),
            ("水干", "suikan robe"),
            ("作務衣", "samue work clothes"),
        ],
    ),
    (
        "western_formal", "洋装フォーマル",
        [
            ("ドレス", "dress"),
            ("ワンピース", "dress"),
            ("制服", "uniform"),
            ("水着", "swimsuit"),
            ("タキシード", "tuxedo"),
            ("チャイナドレス", "cheongsam"),
            ("喪服", "mourning dress"),
            ("花嫁衣装", "wedding dress"),
            ("軍服", "military uniform"),
            ("スーツ", "suit"),
            ("ドレスシャツ", "dress shirt"),
            ("イブニングガウン", "evening gown"),
            ("カクテルドレス", "cocktail dress"),
            ("ボールガウン", "ball gown"),
            ("モーニングコート", "morning coat"),
            ("燕尾服", "tailcoat"),
            ("ウェディングタキシード", "wedding tuxedo"),
            ("フラワーガールドレス", "flower girl dress"),
            ("ブライズメイドドレス", "bridesmaid dress"),
            ("パーティードレス", "party dress"),
            ("ジャンプスーツ", "jumpsuit"),
            ("ロンパース", "romper"),
            ("エンパイアラインドレス", "empire-line dress"),
            ("マーメイドドレス", "mermaid-silhouette dress"),
            ("Aラインドレス", "A-line dress"),
            ("シースドレス", "sheath dress"),
            ("プリンセスラインドレス", "princess-line dress"),
            ("スリップドレス", "slip dress"),
            ("チュチュドレス", "tutu dress"),
            ("ミニドレス", "mini dress"),
            ("マキシドレス", "maxi dress"),
            ("ロングドレス", "long dress"),
            ("バレエレオタード", "ballet leotard"),
        ],
    ),
    (
        "western_casual", "洋装カジュアル",
        [
            ("服", "clothing"),
            ("衣服", "clothing"),
            ("シャツ", "shirt"),
            ("ブラウス", "blouse"),
            ("セーター", "sweater"),
            ("パーカー", "hoodie"),
            ("スカート", "skirt"),
            ("パンツ", "pants"),
            ("ズボン", "pants"),
            ("ベスト", "vest"),
            ("サロペット", "overalls"),
            ("白衣", "lab coat"),
            ("エプロン", "apron"),
            ("Tシャツ", "t-shirt"),
            ("タンクトップ", "tank top"),
            ("キャミソール", "camisole"),
            ("カーディガン", "cardigan"),
            ("ポロシャツ", "polo shirt"),
            ("フランネルシャツ", "flannel shirt"),
            ("デニムパンツ", "denim jeans"),
            ("ショートパンツ", "shorts"),
            ("ワイドパンツ", "wide-leg pants"),
            ("レギンス", "leggings"),
            ("キュロット", "culottes"),
            ("ジャンパースカート", "jumper skirt"),
            ("プリーツスカート", "pleated skirt"),
            ("マキシスカート", "maxi skirt"),
            ("ミニスカート", "mini skirt"),
            ("タイトスカート", "pencil skirt"),
            ("ロングスカート", "long skirt"),
            ("オーバーオール", "dungarees"),
            ("スウェットシャツ", "sweatshirt"),
            ("スウェットパンツ", "sweatpants"),
            ("トラックスーツ", "tracksuit"),
            ("パジャマ", "pajamas"),
            ("ナイトガウン", "nightgown"),
            ("バスローブ", "bathrobe"),
            ("水着（ビキニ）", "bikini"),
            ("競泳水着", "competitive swimsuit"),
            ("ラッシュガード", "rash guard"),
            ("エプロンドレス", "pinafore dress"),
        ],
    ),
    (
        "outerwear", "アウター",
        [
            ("ジャケット", "jacket"),
            ("コート", "coat"),
            ("レインコート", "raincoat"),
            ("ケープ", "cape"),
            ("ボレロ", "bolero jacket"),
            ("マント", "mantle cloak"),
            ("トレンチコート", "trench coat"),
            ("ダウンジャケット", "down jacket"),
            ("デニムジャケット", "denim jacket"),
            ("レザージャケット", "leather jacket"),
            ("ライダースジャケット", "biker jacket"),
            ("ブルゾン", "blouson"),
            ("ピーコート", "pea coat"),
            ("ダッフルコート", "duffle coat"),
            ("チェスターコート", "chesterfield coat"),
            ("ポンチョ", "poncho"),
            ("ウィンドブレーカー", "windbreaker"),
            ("パーカーコート", "parka"),
            ("フリースジャケット", "fleece jacket"),
            ("テーラードジャケット", "tailored blazer"),
            ("ノーカラージャケット", "collarless jacket"),
            ("スタジアムジャンパー", "varsity jacket"),
            ("ボマージャケット", "bomber jacket"),
            ("キルティングコート", "quilted coat"),
            ("ファーコート", "fur coat"),
            ("ケープコート", "cape coat"),
            ("ポンチョコート", "poncho coat"),
        ],
    ),
    (
        "accessory_item", "小物・その他",
        [
            ("靴", "shoes"),
            ("帽子", "hat"),
            ("手袋", "gloves"),
            ("バッグ", "bag"),
            ("スカーフ", "scarf"),
            ("マフラー", "scarf"),
            ("ネクタイ", "necktie"),
            ("蝶ネクタイ", "bow tie"),
            ("ベルト", "belt"),
            ("靴下", "socks"),
            ("ストッキング", "stockings"),
            ("タイツ", "tights"),
            ("ハイヒール", "high heels"),
            ("ブーツ", "boots"),
            ("スニーカー", "sneakers"),
            ("サンダル", "sandals"),
            ("パンプス", "pumps"),
            ("ローファー", "loafers"),
            ("キャップ帽", "baseball cap"),
            ("ベレー帽", "beret"),
            ("中折れ帽", "fedora"),
            ("麦わら帽子", "straw hat"),
            ("ニット帽", "beanie"),
            ("ヘッドドレス", "headdress"),
            ("ティアラ", "tiara"),
            ("かんざし", "kanzashi hair ornament"),
            ("イヤリング", "earrings"),
            ("ネックレス", "necklace"),
            ("ブレスレット", "bracelet"),
            ("指輪", "ring"),
            ("腕時計", "wristwatch"),
            ("サングラス", "sunglasses"),
            ("眼鏡", "glasses"),
            ("マスク", "mask accessory"),
            ("日傘", "parasol"),
            ("傘", "umbrella"),
            ("リュックサック", "backpack"),
            ("ショルダーバッグ", "shoulder bag"),
            ("クラッチバッグ", "clutch bag"),
            ("トートバッグ", "tote bag"),
            ("財布", "wallet"),
        ],
    ),
    (
        "world_traditional", "世界の民族衣装",
        [
            ("ハンボク", "hanbok"),
            ("アオザイ", "ao dai"),
            ("サリー", "sari"),
            ("サルワール・カミーズ", "salwar kameez"),
            ("キルト", "kilt"),
            ("サロン", "sarong"),
            ("カフタン", "kaftan"),
            ("ダシキ", "dashiki"),
            ("ブブ", "boubou robe"),
            ("グアヤベラ", "guayabera shirt"),
            ("ポンチョ（民族衣装）", "traditional poncho"),
            ("チャドル", "chador"),
            ("ヒジャブ", "hijab"),
            ("トーガ", "toga"),
            ("ディアンドル", "dirndl"),
            ("レーダーホーゼン", "lederhosen"),
            ("フラメンコドレス", "flamenco dress"),
            ("バロン", "barong tagalog"),
            ("フセット", "huipil"),
            ("バティックサロン", "batik sarong"),
            ("チマチョゴリ", "chima jeogori"),
            ("パジャマクルタ", "kurta pajama"),
            ("ジェラバ", "djellaba"),
            ("チュニック", "tunic"),
            ("トーブ", "thobe"),
        ],
    ),
    (
        "sportswear_workwear", "スポーツ・ワークウェア",
        [
            ("ユニフォーム", "sports uniform"),
            ("サッカーユニフォーム", "soccer jersey"),
            ("野球ユニフォーム", "baseball uniform"),
            ("バスケットボールユニフォーム", "basketball jersey"),
            ("柔道着", "judo gi"),
            ("空手着", "karate gi"),
            ("剣道着", "kendo uniform"),
            ("体操着", "gym uniform"),
            ("水泳帽", "swim cap"),
            ("エプロン（作業用）", "work apron"),
            ("つなぎ", "coveralls"),
            ("作業着", "work uniform"),
            ("白衣（医療用）", "medical lab coat"),
            ("看護服", "nurse uniform"),
            ("シェフコート", "chef coat"),
            ("消防服", "firefighter uniform"),
            ("警察制服", "police uniform"),
            ("パイロット制服", "pilot uniform"),
            ("エプロンワンピース", "apron dress"),
            ("スキーウェア", "ski suit"),
            ("スノーボードウェア", "snowboard jacket"),
            ("ウェットスーツ", "wetsuit"),
            ("自転車ジャージ", "cycling jersey"),
            ("ヨガウェア", "yoga wear"),
            ("フェンシングユニフォーム", "fencing uniform"),
        ],
    ),
    (
        "costume_fantasy", "コスチューム・ファンタジー衣装",
        [
            ("メイド服", "maid outfit"),
            ("執事服", "butler uniform"),
            ("魔女服", "witch costume"),
            ("騎士鎧", "knight armor"),
            ("プリンセスドレス", "princess gown"),
            ("忍者装束", "ninja outfit"),
            ("侍鎧", "samurai armor"),
            ("巫女装束", "miko shrine maiden outfit"),
            ("天使の衣装", "angel costume"),
            ("悪魔の衣装", "devil costume"),
            ("海賊衣装", "pirate costume"),
            ("吸血鬼マント", "vampire cape"),
            ("スチームパンク衣装", "steampunk outfit"),
            ("宇宙服", "space suit"),
            ("アイドル衣装", "idol stage costume"),
            ("チアリーダー衣装", "cheerleader outfit"),
            ("バニーガール衣装", "bunny girl costume"),
            ("執行官ローブ", "sorcerer robe"),
            ("ゴシックロリータ衣装", "gothic lolita outfit"),
            ("シスター服", "nun habit"),
        ],
    ),
]
